module Giraffe.Deprecated

open Giraffe.ViewEngine

/// This module contains deprecated attributes that are no longer recommended for use in HTML5.

/// These attributes are provided for backward compatibility with older HTML standards.
/// It is recommended to use modern HTML5 attributes and elements instead.
let  _bgcolor = attr "bgcolor"
let _alink = attr "alink"
let _align = attr "align"
let _archive = attr "archive"
let _axis = attr "axis"
let _background = attr "background"
let _border = attr "border"
let _cellpadding = attr "cellpadding"
let _cellspacing = attr "cellspacing"
let _char = attr "char"
let _charoff = attr "charoff"
let _charset = attr "charset"
let _classid = attr "classid"
let _clear = attr "clear"
let _code = attr "code"
let _codebase = attr "codebase"
let _codetype = attr "codetype"
let _compact = attr "compact"
let _declare = attr "declare"
let _event = attr "event"
let _face = attr "face"
let _frame = attr "frame"
let _frameborder = attr "frameborder"
let _hspace = attr "hspace"
let _itemscope = attr "itemscope"
let _itemtype = attr "itemtype"
let _itemprop = attr "itemprop"
let _link = attr "link"
let _longdesc = attr "longdesc"
let _marginheight = attr "marginheight"
let _marginwidth = attr "marginwidth"
let _name = attr "name"
let _nohref = attr "nohref"
let _noshade = attr "noshade"
let _nowrap = attr "nowrap"
let _profile = attr "profile"
let _prompt = attr "prompt"
let _rules = attr "rules"
let _scheme = attr "scheme"
let _scope = attr "scope"
let _scrolling = attr "scrolling"
let _size = attr "size"
let _standby = attr "standby"
let _summary = attr "summary"
let _target = attr "target"
let _text = attr "text"
let _type = attr "type"
let _usemap = attr "usemap"
let _valign = attr "valign"
let _value = attr "value"
let _version = attr "version"
let _vlink = attr "vlink"
let _vspace = attr "vspace"

// Not in Giraffe.ViewEngine
let _nonce = attr "nonce"
let _loading = attr "loading"
let _as = attr "as"
let _nomodule = attr "nomodule"

// Deprecated elements
let  center = tag "center"
let dir = tag "dir"
let font = tag "font"
let frame = tag "frame"
let frameset = tag "frameset"
let noframes = tag "noframes"
let isindex = tag "isindex"
let listing = tag "listing"
let menu = tag "menu"
let nobr = tag "nobr"
let s = tag "s"
let strike = tag "strike"
let u = tag "u"
let xmp = tag "xmp"
let applet = tag "applet"
let basefont = tag "basefont"
let big = tag "big"
let blink = tag "blink"
let marquee = tag "marquee"
let tt = tag "tt"
let acronym = tag "acronym"
let bgsound = tag "bgsound"
let spacer = tag "spacer"
let plaintext = tag "plaintext"